### ISSUE TITLE
Swizzling function?

### ISSUE THREAD

**Issue by SolarLune** [kvartborg/vector#15]
Hello~ I was just thinking that it might be a cool feature to add a swizzling function for vectors, something like:

```
base := vector.Vector{10, 20, 9, 12.3}
xy := base.Swizzle("xy") // xy == {10, 20}
zwy := base.Swizzle("zwy") // zwy == {9, 12.3, 20}
```

Maybe even with negative signs, like `base.Swizzle("x-yz")`? If you're cool with the idea, I could contribute the code, of course.

**Comment by kvartborg** [comment]
Hey @SolarLune, sounds interesting, feel free to create a PR. 
Just to let you know, i haven't settled completely on the overall API of this package yet so things might change, but i think i'm close.

By the way not sure you noticed but i have changed the API a bit since your last contribution. All vector operations are now immutable by default, but if needed you can use the `vector.In` to turn an immutable vector to a mutable one. 
```go
a := vector.Vector{2, 4}
vector.In(a).Add(vector.Vector{1, 2})
// Output of a is {3, 6}
```

**Comment by SolarLune** [comment]
Hello!

It's been awhile - I started working on that swizzle function just today, haha.

And yeah, I've noticed the `vector.In()` function - seems like a sensible middle ground for performance while also not drastically reworking the API. Good work on that!

With this in mind, I'm pretty sure I have the swizzling function written out OK, but it seems like it would be impossible to swizzle a mutable vector as writing to the vector would destroy the data to read from (i.e. if you have the vector {0, 2, 4} and swizzle it with the string "zyx", then it would be impossible to put 0 in the third slot as "x" would then be "4"). 

Do you think it would be sensible to just leave out the Swizzle function for `MutableVector` because of this?

**Comment by kvartborg** [comment]
Hi @SolarLune,

I see your point, i think for a starter that it's ok to focus on the `Vector` type. 
Then we can explore the implementation and see how it fits with `MutableVector` afterwards.

The only concern i have is how it will perform, i will assume that the parsing of the string input will be pretty slow compared to the naive implementation of a Swizzle function like below.

```go
func SwizzleZYX(a Vector) Vector {
    return Vector{a[2], a[1], a[0]}
}
```

I like your suggestion because it's what you would expect to be possible from other libraries/languages and its good in terms of developer experience. 
But it has to be somewhat performant as well in order to be used as standard.

I think both goals are achievable. An idea could be to construct a function the first time Swizzle gets called on a `Vector`. The function should contain the swizzle logic for a given input string. After the first run the constructed function could then be saved in a map where the key is the input string and the value is the constructed function. All subsequent calls can then make a lookup and execute the swizzle without any parsing of the string again (Benchmarks should be used to verify this idea compared to parsing each time).
There is some problems with the above idea though. Should it be possible to clean the cached functions somehow? Or can it be ignored? The solution is also pretty complex, so it has to perform really well to be worth it. Probably more problems i haven't thought about..

What are your thoughts on this?

> Note, this is just my thoughts, i haven't tried or check benchmarks for any of this and it is definitely not the only solution, feel free to contribute your own ideas/implementation to the problem.

**Comment by kvartborg** [comment]
I have run a quick benchmark based on the `SwizzleZYX` function presented above and compared it to the simplest `Swizzle('zyx')` function i could think of, it does not support negative signs though and there should probably be some validation of the input string as well. This example is made to get an idea of the difference in execution time between the baseline and the suggested idea.

```go
func (v Vector) Swizzle(s string) Vector {                                                                                                                                          
    result := make(Vector, len(s))                                                                                                                                                 
                                                                                                                                                                                       
    for i, r := range s {                                                                                                                                                          
        result[i] = v[r-'x']                                                                                                                                                           
    }                                                                                                                                                                                  
                                                                                                                                                                                       
    return result                                                                                                                                                                      
}     
```

The benchmark results are the following:
```go
BenchmarkSwizzleZYX             1000000000               0.3455 ns/op
BenchmarkVector_Swizzle           34097654                31.81 ns/op
```
As it can be seen from the result above parsing the input will take substantial longer time than the baseline example. I still think it is within a usable limit, it's just important that the cost of its us are considered.
Not sure if a faster implementation is possible, but ideas are very welcome?

**Comment by SolarLune** [comment]
Ah, yeah, I see - it seems that string-based swizzling would probably always be a bit slow.

Considering the usual use case is simply to switch values in a 3D vector, I would be fine with just basic swizzling and can do without negation or longer vectors. 

Also, since, usually, the swizzling string is just made to be human-readable, it would also be faster to use the indices directly rather than passing a string indicating the order with "x", "y", and "z" runes.

The API taking numbers is a bit odd, but it is way faster:

```go
func newSwizzle(a []float64, x, y, z int) []float64 {

	if x < 0 || x > 2 {
		panic("x must be a valid index in a 3D vector")
	}

	if y < 0 || y > 2 {
		panic("y must be a valid index in a 3D vector")
	}

	if z < 0 || z > 2 {
		panic("z must be a valid index in a 3D vector")
	}

	return []float64{a[x], a[y], a[z]}

}

```

To use it, you would do something like:

```go
original := vector.Vector{0, 2, 19}
swizzledZYX := original.Swizzle(2, 1, 0) // Contains [19, 2, 0] now
swizzledZZY := original.Swizzle(1, 0, 1) // Contains [2, 0, 2] now
```

The test results:

```
BenchmarkSwizzlingNew-12        1000000000               0.3350 ns/op          0 B/op          0 allocs/op
BenchmarkSwizzlingZYX-12        1000000000               0.3224 ns/op          0 B/op          0 allocs/op
```

What do you think?

**Comment by kvartborg** [comment]
Thats actually a really good idea! 

You can even extend it to work with n-dimensional vectors, not sure how much it will add to the execution time, but i think it is worth to explore?
I would also consider returning an error instead of panics, i'm not that fond of having code that can result in exits. I like to be explicit with errors when things can go wrong.

```go
func (Vector) Swizzle(...int) (Vector, error)
```

Another benefit i like with your suggestion, is that it is possible to make it as readable using consts. See example below.

```go
const (
    x = iota
    y
    z
    // ...
)

base := Vector{1, 2, 3}
swizzled := base.Swizzle(z, y, x) // almost equal to the string based in terms of readability
swizzled[x] // Output: 3
```

**Comment by SolarLune** [comment]
Hmm, looks like you can't pass -0 as an int argument, as -0 gets converted at compile time to a standard, positive (?) zero. At least, that seems to be what's happening. Also, N-length vectors result in an allocation, which slows things down a bit since we can't simply return a 3D vector. I do like returning an error instead of panicking, though - this is what I have so far:

```go

func ogSwizzle(a []float64, x, y, z int) ([]float64, error) {

	if x < 0 || x > 2 {
		return nil, ErrNotValidSwizzleIndex
	}

	if y < 0 || y > 2 {
		return nil, ErrNotValidSwizzleIndex
	}

	if z < 0 || z > 2 {
		return nil, ErrNotValidSwizzleIndex
	}

	return []float64{a[x], a[y], a[z]}, nil

}

func newSwizzleN(a []float64, indices ...int) ([]float64, error) {

	vec := make([]float64, len(indices))

	for i := 0; i < len(indices); i++ {

		ind := indices[i]
		if ind < 0 {
			ind = -ind
			if ind >= len(a) {
				return nil, ErrNotValidSwizzleIndex
			}
			vec[i] = -a[ind]
		} else {
			if ind >= len(a) {
				return nil, ErrNotValidSwizzleIndex
			}
			vec[i] = a[ind]
		}

	}

	return vec, nil

}

```

And the benchmark results:

```
BenchmarkSwizzlingOG-12         1000000000               0.3078 ns/op          0 B/op          0 allocs/op
BenchmarkSwizzlingN-12          18201237                63.59 ns/op           24 B/op          1 allocs/op
BenchmarkSwizzlingZYX-12        1000000000               0.3384 ns/op          0 B/op          0 allocs/op
```

If I get rid of inversion, BenchmarkSwizzlingN's results are:
```
BenchmarkSwizzlingN-12          29341386                56.98 ns/op           24 B/op          1 allocs/op
```

However, I do like the idea of using const values to swap in for using x, y, and z for readability - that's an easy-to-implement solution for the developer.

**Comment by kvartborg** [comment]
Ah, i see, that sounds like the compiler, not sure it can be achieved easily then.. It would have been a need feature though.

Yeah, thats slower than what i expected. I agree that we should optimize for the most common cases, which probably will be vectors from 1..3 dimensions. But i still think it should incorporate the n-dimensional logic, the reason being that all other operations does. 
A way to achieve this without sacrificing too much performance, is to add the common cases before the n-dimensional implementation. I do this in `arithmetic.go` for almost all functions. It will hurt performance a bit as go's compiler can't optimize larger function as well. But typically it's still fast enough to be worth it.

**Comment by SolarLune** [comment]
OK, so this is the current approach:

```go

func newSwizzleN(a []float64, indices ...int) ([]float64, error) {

	for _, i := range indices {
		if i >= len(a) {
			return nil, ErrNotValidSwizzleIndex
		}
	}

	switch len(indices) {

	case 0:
		return []float64{}, nil
	case 1:
		return []float64{a[indices[0]]}, nil
	case 2:
		return []float64{a[indices[0]], a[indices[1]]}, nil
	case 3:
		return []float64{a[indices[0]], a[indices[1]], a[indices[2]]}, nil
	case 4:
		return []float64{a[indices[0]], a[indices[1]], a[indices[2]], a[indices[3]]}, nil
	default:

		vec := make([]float64, len(indices))

		for i := 0; i < len(indices); i++ {

			ind := indices[i]
			if ind >= len(a) {
				return nil, ErrNotValidSwizzleIndex
			}
			vec[i] = a[ind]

		}

		return vec, nil

	}

}

```

Has an allocation that I'm not certain can be removed; could be due to the compiler not being able to determine at compile-time how long the returned slice is, so it can't do any special optimizations. 

Here's the speed results:
```
BenchmarkSwizzlingOG-12         1000000000               0.3220 ns/op          0 B/op          0 allocs/op
BenchmarkSwizzlingN-12          27274282                46.67 ns/op            8 B/op          1 allocs/op
BenchmarkSwizzlingZYX-12        1000000000               0.3274 ns/op          0 B/op          0 allocs/op
```

**Comment by kvartborg** [comment]
I think your close to what is possible with an n-dimensional implementation, good work! It would probably make sense to move it into a PR at this point, then we can figure out the final details.

**Comment by SolarLune** [comment]
Alrighty - I've opened a PR at #24. Thanks for your help so far!

**Comment by kvartborg** [comment]
Cool, I will take a look at your PR now. Thank you for your good ideas and contribution!

**Comment by SolarLune** [comment]
No problem, and thanks for the review and merge~!
