### ISSUE TITLE
Angle() function

### ISSUE THREAD

**Issue by SolarLune** [kvartborg/vector#5]
Hello! 

A function to return the angle between two Vectors would be highly useful, particularly in 2D; any plans to add this? I'm not too hot on my math, but I can take a crack at it if you'd find it useful.

**Comment by kvartborg** [comment]
I agree, it would be very useful. Your welcome to take a crack at it! 

It is important that the solution works with both 2D and 3D vectors. The API could look something like the example below?

```go
angle, err := vector.Angle(v1, v2)
// and
angle, err := v1.Angle(v2)
```

**Comment by SolarLune** [comment]
Adding the Angle() function via PR. My proposed Angle() function returns the vector of rotation to get the angle from one vector to another, as well; seems like it might be good for Vector.Rotate() to take Vectors to rotate by, rather than being fixed axes.

**Comment by SolarLune** [comment]
Updated with a slight improvement to the verbage of the docs for the Angle() function.

**Comment by kvartborg** [comment]
> Seems like it might be good for Vector.Rotate() to take Vectors to rotate by, rather than being fixed axes.

This is a great idea! Will look into that.
