### ISSUE TITLE
Invert() function

### ISSUE THREAD

**Issue by SolarLune** [kvartborg/vector#6]
Hello, again; I think it'd be useful to have an `invert()` function for Vectors; currently, it's a bit onerous to type: 
```
vector[0] = -vector[0]
vector[1] = -vector[1]
```

when I want to invert a vector. Would it be OK for me to add a PR for this?

**Comment by kvartborg** [comment]
Sure, go ahead 👍

**Comment by SolarLune** [comment]
Opened a new PR for this; updated it immediately with a docstring for both Invert() functions, whoops. Let me know if there's something missing~
